# Generated by Django 4.2.8 on 2024-12-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_birthday_user_gender_user_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='unknown', max_length=150, verbose_name='이름'),
        ),
    ]
